apiVersion: v1
kind: Service
metadata:
  name: zabbix
  labels:
    app: zabbix
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: zabbix-web
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-db
  labels:
    app: zabbix
    tier: db
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: zabbix-db
  selector:
    name: zabbix-db
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  labels:
    app: zabbix
spec:
  ports:
  - port: 10051
    targetPort: 10051
    name: zabbix-trapper
  - port: 10052
    targetPort: 10052
    name: zabbix-jmx
  selector:
    name: zabbix-server
