apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rocketchat-database
spec:
  template:
    metadata:
      labels:
        app: rocketchat
        tier: backend
    spec:
      containers:
      - name: rocketchat-database
        image: mongo
        command: ["/bin/sh", "-c"]
        args: ["mongod --smallfiles --oplogSize 128"]
        ports:
          - name: mongo
            containerPort: 27017
        volumeMounts:
        - name: rocketchat-storage
          mountPath: /data/db
      volumes:
      - name: rocketchat-storage
        persistentVolumeClaim:
          claimName: rocketchat-storage-pvc
