apiVersion: v1
kind: Service
metadata:
  labels:
    app: onlyoffice-documentserver
  name: onlyoffice-documentserver
spec:
  externalIPs:
    - "191.36.8.4"
    - "191.36.8.5"
    - "191.36.8.6"
    - "191.36.8.7"
    - "191.36.8.8"
  ports:
    - name: onlyoffice
      port: 8080
      protocol: TCP
      targetPort: 443
  selector:
    app: onlyoffice-documentserver
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
      app: onlyoffice-postgresql-bd
  name: onlyoffice-postgresql-bd
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
      app: onlyoffice-postgresql-bd
---
apiVersion: v1
kind: Service
metadata:
  labels:
      app: onlyoffice-rabbitmq
  name: onlyoffice-rabbitmq
spec:
  ports:
  - name: rabbitmq
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
      app: onlyoffice-rabbitmq

---
apiVersion: v1
kind: Service
metadata:
  labels:
      app: onlyoffice-redis
  name: onlyoffice-redis
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
      app: onlyoffice-redis
      
