apiVersion: v1
kind: Service
metadata:
  labels:
    app: openldap
  name: openldap
spec:
  externalIPs:
    - "191.36.8.4"
    - "191.36.8.5"
    - "191.36.8.6"
    - "191.36.8.7"
    - "191.36.8.8"
  ports:
    - name: ldap
      port: 389
      protocol: TCP
      targetPort: 389
  selector:
    app: openldap-openldap
  type: LoadBalancer
